### ISSUE TITLE
Please clarify how to use EXTRA_SETTINGS_DEFAULTS

### ISSUE THREAD

**Issue by swasher** [fabiocaccamo/django-extra-settings#88]
> django==4.2
django-extra-settings==0.9.1
Python 3.11.2

I'm use this extension and it work fine.

Howerer, I can't understand how to use default settings via `settings.py`.  Steps what i do:

1. drop db, then `makemigraions` and `migrate` (at this point all work fine, and `extra_settings_setting` db is empty)
2. Add section so settings.py:
```python
EXTRA_SETTINGS_DEFAULTS = [
    {
        "name": "margin_top",
        "type": 'int',
        "value": "7",
    },
]
```
3; Start server by `manage.py server` and got following error:
```
> python.exe C:\Users\OLEKSII\GitHub\printMES\manage.py runserver 127.0.0.1:8000 
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\OLEKSII\.virtualenvs\printMES-wR4SQlij\Lib\site-packages\django\db\models\query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\OLEKSII\.virtualenvs\printMES-wR4SQlij\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
extra_settings.models.Setting.DoesNotExist: Setting matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\OLEKSII\.virtualenvs\printMES-wR4SQlij\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "extra_settings_setting_name_key"
DETAIL:  Key (name)=(MARGIN_TOP) already exists.
```

Checking  `extra_settings_setting` db i see a `MARGIN_TOP` record.

Can you add more clear documentatoin how to use `EXTRA_SETTINGS_DEFAULTS`?
Do I understand correctly that I can use `EXTRA_SETTINGS_DEFAULTS` for maintaining default values set with the source code?

<a href="https://dashboard.polar.sh/fabiocaccamo/django-extra-settings/issues/88">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/88/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-extra-settings/issues/88/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@swasher sorry for the late answer.

`EXTRA_SETTINGS_DEFAULTS` should be automatically created in the database on app ready if they don't exist yet.

https://github.com/fabiocaccamo/django-extra-settings/blob/main/extra_settings/models.py#L99

I fixed a problem that could interfere with `EXTRA_SETTINGS_DEFAULTS` setting, could you please upgrade to the latest version (`0.10.0`) and tell me if it works as expected or not?

**Comment by swasher** [comment]
Thank you very mush, now working like a charm!

**Comment by swasher** [comment]
Thank you, now work like a charm!

**Comment by mcrot** [comment]
Hi, thanks for this useful package! 

I still have problems to understand how `EXTRA_SETTINGS_DEFAULTS` is supposed to work,
Does this only work on the first migration of  `extra_settings`?

My use case is that the first migration has already been run and I would like to change `EXTRA_SETTINGS_DEFAULTS`,
e.g. add a validator or change the default value. I would like to ensure that a setting, if it does not exist yet, will be created with the new default value. Is it supposed to work like this?

**Comment by fabiocaccamo** [comment]
@mcrot yes, they work on `post_migrate`, but if you already have settings in the database they are not overwritten by defaults.

If you want some default settings to be applied to the database you have to delete those settings from the database and re-run migrations.

**Comment by mcrot** [comment]
Now I understand. I can run `migrate` and create missing settings even if there are no pending migrations (migrations which haven't been applied yet). Before I thought pending migrations are needed in order to have the signal `post_migrate`. Thanks, @fabiocaccamo !

**Comment by fabiocaccamo** [comment]
@mcrot exactly, the `post_migrate` signal in Django is triggered every time the `migrate` command is run.
